#include: package:pedantic/analysis_options.1.8.0.yaml
#analyzer:
#  exclude: [build/**]
#  strong-mode:
#    implicit-casts: false
#    implicit-dynamic: false
#  errors:
#    undefined_prefixed_name: ignore
#
#linter:
#  rules:
#    - camel_case_types